---
- name: Install httpd web server
  hosts: web_servers
  
  tasks:
  
  - name: install httpd
    dnf:
      name: httpd
      state: latest

  - name: add index.html
    template:
      src: index.html.j2
      dest: /var/www/html/index.html

  - name: httpd running
    service:
      name: httpd
      enabled: true
      state: started


